### ISSUE TITLE
Search not working when not deployed to root

### ISSUE THREAD

**Issue by alex-hedley** [statiqdev/CleanBlog#36] opened 2023-10-13 12:02 UTC
In `appsettings.json` `{ "GenerateSearchIndex": true }` doesn't go to deployed path.

If you are hosting via GitHub pages but not on the root repo what are the settings needed to make search work?

**Comment by daveaglick** [comment] 2023-12-22 15:41
Sorry for the delay! Finally trying to get caught up on some of these issues. I'm not quite sure I understand the problem here yet - generally setting a deployed path changes links so that they take into account that URLs need a subpath, not where the actual files are output (they'll still go to the `output` directory). Is the problem here that the link to the search JavaScript file doesn't contain the correct subpath, and therefore the front-end can't find the search index? Or is it that when you specify an alternate `RootPath` that contains your `input`, `output`, etc. directories locally that the search index doesn't go there like it should?

**Comment by alex-hedley** [comment] 2023-12-22 16:07
Sorry, I should have provided a working example.

For instance if I was to deploy via GitHub Pages to the route project like [alex-hedley.github.io](https://github.com/alex-hedley/alex-hedley.github.io/) it would work.

But if I want to do it in another repo like [blog](https://github.com/alex-hedley/blog) it doesn't work. Maybe I'm missing a setting?

My POC is here: [statiqweb-example](https://github.com/alex-hedley/statiqweb-example) which is deployed at [https://alex-hedley.github.io/statiqweb-example/](https://alex-hedley.github.io/statiqweb-example/)

When I type in a search query and press <kbd>Enter</kbd> it goes to `https://alex-hedley.github.io/search?query=mermaid` not `https://alex-hedley.github.io/statiqweb-example/search?query=mermaid`.

Do I only need to add the following to my [appsettings.json](https://github.com/alex-hedley/statiqweb-example/blob/main/src/appsettings.json)?

```json
  "GenerateSearchIndex": true,
  "LinkRoot": "/statiqweb-example"
```

I've tried setting `SearchIncludeHost` in [WebKeys.cs](https://github.com/statiqdev/Statiq.Web/blob/0d10c5e47f865d9f4e06bb552f27e2242425a624/src/Statiq.Web/WebKeys.cs#L111C14-L111C14) but does that include the `LinkRoot` too?

**Comment by daveaglick** [comment] 2023-12-22 16:35
Got it! And I can replicate locally. This is actually a bug in the CleanBlog theme, so I'll move this issue there. The problem is that the theme files aren't accounting for the `LinkRoot` setting when linking to the search page or indexes. Your configuration file above should be fine once this bug is fixed (which I'm doing now).

**Comment by alex-hedley** [comment] 2023-12-22 16:36
Legend,thank you.

**Comment by daveaglick** [comment] 2023-12-22 16:40
The fix is committed to the theme, but it's a relatively small one so it might just be easier to copy it into your theme copy than check everything out:

![image](https://github.com/statiqdev/CleanBlog/assets/1020407/8d0a8774-0d10-4731-8c35-12a3524e8895)

Let me know if you have any other issues!

**Closed as completed by daveaglick** 2023-12-22 16:40 UTC
Labels: ⚠ Bug

**Comment by alex-hedley** [comment] 2023-12-22 16:54
I've got **CleanBlog** as a submodule so

locally

`cd src/theme`
`cd fetch`

CI/CD

```yml
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
```

Looks like it's still pulling [af2f289](https://github.com/statiqdev/CleanBlog/commit/af2f28911f173db30baf8efc66ede259a9c79ceb) instead of [ad63989](https://github.com/statiqdev/CleanBlog/commit/ad639891c4469a2c9fc1d16b0ef8f99e975e82d8) when checking the `▽ Fetching submodules` in my pipeline https://github.com/alex-hedley/statiqweb-example/actions/runs/7302063613/job/19899968395 but that's more a me problem I'll look into.

Thanks for the quick fix, appreciate it.

_Edit_

Forgot to do:

`git submodule update --remote --recursive --merge`
